# Generated by Django 2.2.1 on 2020-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, upload_to='list_image'),
        ),
    ]
