# Generated by Django 2.2.1 on 2020-07-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200701_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
