# Generated by Django 2.2.1 on 2020-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200706_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
