# Generated by Django 2.2.1 on 2020-07-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200706_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='todolist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ToDoList'),
        ),
    ]
